version: "3.3"
services:
  # pubsub:
  #   container_name: "pubsub"
  #   image: solace/solace-pubsub-standard:latest
  #   shm_size: 1g
  #   ulimits:
  #     core: 1
  #     nofile:
  #       soft: 2448
  #       hard: 38048
  #   deploy:
  #     restart_policy:
  #       condition: on-failure
  #       max_attempts: 1
  #   ports:
  #     - '1883:1883'
  #     - '8080:8080'
  #     - '8008:8008'
  #   environment:
  #     - username_admin_globalaccesslevel=admin
  #     - username_admin_password=admin
  #     - system_scaling_maxconnectioncount=100
    # logging:
    #   driver: none

  api:
    container_name: "api"
    build: .
    logging:
      driver: none
    expose:
      - 3000
    ports:
      - 3000:3000
    # depends_on:
    #   - pubsub
    tty: true
    environment:
      - BROKER_HOST=testbed.code-lab.org
      - BROKER_PORT=1883
      - SLEEP=0

  mqtt_ws_tunnel:
    container_name: "mqtt_ws_tunnel"
    build: ./mqtt_ws_tunnel
    logging:
      driver: none
    expose:
      - 3000
    ports:
      - 2000:2000
    # depends_on:
    #   - pubsub
    tty: true
    environment:
      - BROKER_HOST=testbed.code-lab.org
      - BROKER_PORT=1883
      - SLEEP=0

  control:
    build: ./control
    logging:
      driver: none
    expose:
      - 8000
    depends_on:
      - api
      # - pubsub
    ports:
      - 8000:8000
    environment: 
      - API_HOST=localhost
      - API_PORT=3000
      - WS_HOST=localhost
      - WS_PORT=2000
      - BROKER_HOST=testbed.code-lab.org
      - BROKER_PORT=1883
      - SLEEP=0

  nginx:
    image: nginx:1.13.7
    logging:
      driver: none
    ports:
      - '80:80'
    depends_on:
      - control
      - api
      - mqtt_ws_tunnel
      # - pubsub
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro

  vapsat:
    container_name: "vapsat"
    build:
      context: ./components/vapsat
      dockerfile: Dockerfile
    # tty: true
    restart: always
    depends_on:
      - api
    environment:
      - BROKER_HOST=testbed.code-lab.org
      - BROKER_PORT=1883
      - SLEEP=3

  river-node:
    container_name: "river-node"
    build:
      context: ./components/river-node
      dockerfile: Dockerfile
    # tty: true
    restart: always
    depends_on:
      - api
    environment:
      - BROKER_HOST=testbed.code-lab.org
      - BROKER_PORT=1883
      - SLEEP=3

  weather-node:
    container_name: "weather-node"
    build:
      context: ./components/weather-node/Node
      dockerfile: Dockerfile
    # tty: true
    restart: always
    depends_on:
      - api
    environment:
      - BROKER_HOST=testbed.code-lab.org
      - BROKER_PORT=1883
      - SLEEP=3

  mattsat:
    container_name: "mattsat"
    build:
      context: ./components/mattsat
      dockerfile: Dockerfile
    # tty: true
    restart: always
    depends_on:
      - api
    ports:
      - 8080:8080
    environment:
      - BROKER_HOST=testbed.code-lab.org
      - BROKER_PORT=1883
      - SLEEP=3
