version: "3.3"
services:
  # pubsub:
  #   container_name: "pubsub"
  #   image: solace/solace-pubsub-standard:latest
  #   shm_size: 1g
  #   ulimits:
  #     core: 1
  #     nofile:
  #       soft: 2448
  #       hard: 38048
  #   deploy:
  #     restart_policy:
  #       condition: on-failure
  #       max_attempts: 1
  #   ports:
  #     - '1883:1883'
  #     - '8080:8080'
  #     # - '55555:55555'
  #     - '8008:8008'
  #   environment:
  #     - username_admin_globalaccesslevel=admin
  #     - username_admin_password=admin
  #     - system_scaling_maxconnectioncount=100
  #   logging:
  #     driver: none

  api:
    container_name: "api"
    build: .
    expose:
      - 3000
    ports:
      - 3000:3000
      - 2000:2000
    tty: true
    environment:
      - BROKER_HOST=testbed.code-lab.org

  control:
    build: ./control
    logging:
      driver: none
    expose:
      - 8000
    depends_on:
      - api
    ports:
      - 8000:8000
    environment: 
      - API_HOST=api

  nginx:
    image: nginx:1.13.7
    logging:
      driver: none
    ports:
      - '80:80'
    depends_on:
      - control
      - api
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro

  sensor_arroyo:
    container_name: "sensor_arroyo"
    build:
      context: ./components/sensor
      dockerfile: Dockerfile
    tty: true
    restart: always
    depends_on:
      # - pubsub
      - api
    environment:
      - BROKER_HOST=testbed.code-lab.org
      - SLEEP=5
      - DATASET=arroyo
      - LAT=80
      - LON=10

  sensor_valyermo:
    container_name: "sensor_valyermo"
    build:
      context: ./components/sensor
      dockerfile: Dockerfile
    tty: true
    restart: always
    depends_on:
      # - pubsub
      - api
    environment:
      - BROKER_HOST=testbed.code-lab.org
      - SLEEP=5
      - DATASET=valyermo
      - LAT=0
      - LON=90

  sensor_hansen:
    container_name: "sensor_hansen"
    build:
      context: ./components/sensor
      dockerfile: Dockerfile
    tty: true
    restart: always
    depends_on:
      # - pubsub
      - api
    environment:
      - BROKER_HOST=testbed.code-lab.org
      - SLEEP=5
      - DATASET=hansen
      - LAT=81
      - LON=40

  sensor_sepulveda:
    container_name: "sensor_sepulveda"
    build:
      context: ./components/sensor
      dockerfile: Dockerfile
    tty: true
    restart: always
    depends_on:
      # - pubsub
      - api
    environment:
      - BROKER_HOST=testbed.code-lab.org
      - SLEEP=5
      - DATASET=sepulveda
      - LAT=0
      - LON=50

  satellite_equitorial:
    container_name: "satellite_equitorial"
    build:
      context: ./components/satellite
      dockerfile: Dockerfile
    tty: true
    restart: always
    depends_on:
      # - pubsub
      - api
    environment:
      - BROKER_HOST=testbed.code-lab.org
      - SLEEP=5
      - ORBIT=equitorial
      - FIELD_OF_VIEW=200

  satellite_polar:
    container_name: "satellite_polar"
    build:
      context: ./components/satellite
      dockerfile: Dockerfile
    tty: true
    restart: always
    depends_on:
      # - pubsub
      - api
    environment:
      - BROKER_HOST=testbed.code-lab.org
      - SLEEP=5
      - ORBIT=polar
      - FIELD_OF_VIEW=200

  groundstation:
    container_name: "groundstation"
    build:
      context: ./components/groundstation
      dockerfile: Dockerfile
    tty: true
    restart: always
    depends_on:
      # - pubsub
      - api
    environment:
      - BROKER_HOST=testbed.code-lab.org
      - SLEEP=5
